# Init of code
#from .simils import *
#from .SimILS import *
#from .SimILSObjects import *
#from test import *
#from . import simils#,SimILS,SimILSObjects
#from .SimILS import splittingPolicy
#from .SimILSObjects import ClassSimILSSolution
#from SimILS.stage1 import CWSInterface
#from cws_custom import cwsInterface